# Use Node.js as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Verify Yarn is installed (optional)
RUN yarn --version

# Install NestJS CLI globally
RUN yarn global add @nestjs/cli

# Expose a port (if the app runs on a specific port, e.g., 3000)
EXPOSE 3000

# Run a default command
CMD ["yarn", "start"]